### ISSUE TITLE
использование на линукс системах

### ISSUE THREAD

**Issue by perdakovich** [Rast1234/VOffline#11]
как использовать вашу программу на линукс системах?

**Comment by perdakovich** [comment]
пытался сбилдить с помощью 

```
nuget restore
msbuild VOffline.sln

```
получил вот такие файлы в bin:
```
appsettings.json  VOffline.deps.json  VOffline.pdb                     VOffline.runtimeconfig.json
log4net.config    VOffline.dll        VOffline.runtimeconfig.dev.json
```

что дальше? наверное я что-то делаю не так?

**Comment by Rast1234** [comment]
нужен dotnet sdk 2.1, может быть 2.2 тоже подойдет. сборка командой dotnet build, запуск командой dotnet run $имя_проекта или напрямую dotnet VOffline.dll

msbuild на линуксе это наверное из mono? он не нужен и скорее всего не заведется, я не проверял

**Comment by perdakovich** [comment]
`dotnet build` в папке проекта? там где .sln файл?

**Comment by Rast1234** [comment]
да, либо передать ему имя sln или csproj файла как параметр

**Comment by perdakovich** [comment]
да, msbuild это из mono
я пытался нагуглить способ компилировать .sln файлы на линуксе)

**Comment by perdakovich** [comment]
хорошо, спасибо, попробую!

**Comment by perdakovich** [comment]
нужно было прописать вот такое, чтоб запустилось
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

без этого была ошибка про ICU System.Globalization что-то там.

ввёл все значения в конфиг, теперь вот такая ошибка:

```
2023-06-18 13:25:02,942 [  1] DEBUG  Started
2023-06-18 13:25:03,059 [  1] DEBUG  FileCache.GoogleCredentials.json loaded value
2023-06-18 13:25:03,068 [  1] DEBUG  request receipt 1
2023-06-18 13:25:03,854 [  1] DEBUG  request receipt 2
2023-06-18 13:25:04,010 [  1] DEBUG  request non-refreshed token
2023-06-18 13:25:04,226 [  1] DEBUG  refresh token
2023-06-18 13:25:04,311 [  1] FATAL  Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at VOffline.Services.Token.Vk.VkHttpRequests.RefreshToken(String token, String receipt, ILog log) in /home/user/Downloads/VOffline/VOffline/Services/Token/Vk/VkHttpRequests.cs:line 65
   at VOffline.Services.Token.Vk.VkTokenReceiver.GetToken(ILog log) in /home/user/Downloads/VOffline/VOffline/Services/Token/Vk/VkTokenReceiver.cs:line 24
   at VOffline.Services.Token.TokenMagic.GetTokenFromScratch(ILog log) in /home/user/Downloads/VOffline/VOffline/Services/Token/TokenMagic.cs:line 29
   at VOffline.Services.Logic.Run(CancellationToken token, ILog log)
in /home/user/Downloads/VOffline/VOffline/Services/Logic.cs:line 52
   at VOffline.Program.Main(String[] args) in /home/user/Downloads/VOffline/VOffline/Program.cs:line 88

```

**Comment by Rast1234** [comment]
фиг знает что это. вообще, проект давно не обновлялся, я не уверен что оно даже авторизоваться сможет

**Comment by perdakovich** [comment]
а есть альтернативы? 
знаю про GDPR экспорт данных от самого ВК, но не нашёл там "Избранное"...
+нельзя экспортировать данные других людей

**Comment by Rast1234** [comment]
без понятия, я забросил потому что мне стало просто пофигу на то, что осталось в вк...

**Comment by yo8z6gv** [comment]
> без понятия, я забросил потому что мне стало просто пофигу на то, что осталось в вк...

"осталось". а ведь вк норм такой файлообменник и фотохостинг. изображения продолжают хранится и активны даже если и первоисточник заблокирован полностью, вплоть до удаления этого изображения самим пользователем.
а как файлообменник, несмотря на бан пользователя продолжает оставаться доступным. нужно грузить в сообщества. аналогично и с видео, но везде нужны доступ общий, тогда и аккаунт не нужен для воспроизведения.

собснтвенно всегда использовал твой софт чтобы просканировать все свои такие записи для размещения уже на своих ресурсах или скидыванием в лс. некоторым удобнее через вк смотреть видео, нежели телега, а на ют слишком мощные фильтры.

так в вк видео я загрузил на десятки тб. изображений может на несколько тб. а файлов точно около или больше тб.

**Comment by yo8z6gv** [comment]
например даже 64гб оперативки, 13900 процессора не хватает и крашится браузер если слишком много прогрузить и попытаться это дело сохранить

**Comment by Rast1234** [comment]
ну, видишь, у всех разные потребности :) я пилил для себя - только чтобы вытянуть несколько групп с музыкой, да свою страницу. в итоге наигрался, да забил. может когда-то вернусь чтобы обновить, да удалиться из вк окончательно.


кстати, рад, что кому-то эта штука пригодилась в таких масштабах!

**Comment by yo8z6gv** [comment]
> да удалиться из вк окончательно

эх.. а меня сам вк постоянно выпиливает. ни одного аккаунта настоящего не осталось, все твины и покупные) тк самостоятельная регистрация обязательно приводит к бану по подозрительной активности. нужна "отложка".
а еще недавно усугубил вк это, теперь телефон просят не только по запросу всей инфы о акке, но и при смене имени, фамилии, создании приложений вроде и еще в некоторых местах. раньше можно было забыть про номер телефона. а теперь постоянно спрашивают, по сути кроме базовых вещей -- ничего не сделать.
жалко что с виртуальными номерами не так просто как с аккаунтами

**Comment by yo8z6gv** [comment]
смене почте еще спрашивают телефон. раньше можно было привязать почту чтобы смотреть уведомления с других аккаунтов, тк авторизация в приложениях мультиакка тоже "подозрительна")
