### ISSUE TITLE
Ошибка логина

### ISSUE THREAD

**Issue by apan65** [Rast1234/VOffline#5]
Пароль\логин верный, ЧЯДНТ?
```
2021-04-21 01:37:27,108 [  1] DEBUG  request non-refreshed token
2021-04-21 01:37:27,456 [  1] FATAL  System.InvalidOperationException: GetNonRefreshedToken bad response: Unauthorized
{"error":"invalid_client","error_description":"Неправильный логин или пароль","error_type":"username_or_password_is_incorrect"}
```

**Comment by Rast1234** [comment]
А id приложения правильный?

Покажи пожалуйста конфиг, естественно без логина, пароля и id. И как запускаешь тоже

**Comment by apan65** [comment]
Так там в конфиге ничего особо и нет, кроме логина\пароля. Там можно же те же цели и режимы оставить что и по-умолчанию в конфиге стоят, всё-равно должно работать же?

**Comment by Rast1234** [comment]
да, я по памяти отвечал, с более старой тулзой перепутал)

сейчас запустил проверил все работает. попробуй удалить файлы кэша в папке с приложением:

`FileCache.*.json`

**Comment by apan65** [comment]
> 
> 
> да, я по памяти отвечал, с более старой тулзой перепутал)
> 
> сейчас запустил проверил все работает. попробуй удалить файлы кэша в папке с приложением:
> 
> `FileCache.*.json`
> 
> а может быть есть какие-нибудь грабли с вариантами логина. я почту использую, по номеру телефона не пробовал даже

То же самое, по сути готовый релиз 0.3версии кэшев не имеет, захожу по почте и паролю, даже проверил разлогинившись заходит ли на сайт. Может что с самим акком или я что-то упускаю?

**Comment by Rast1234** [comment]
двухфакторной авторизации нет? я сам не эксперт по работе с ВК, может там есть еще какие-нибудь настройки усложняющие вход

**Comment by apan65** [comment]
> 
> 
> двухфакторной авторизации нет? я сам не эксперт по работе с ВК, может там есть еще какие-нибудь настройки усложняющие вход

Не, нет, заходит по паре логин\пароль, с новорега то же самое. Может скините сборку которой сами пользуетесь? Или

**Comment by Rast1234** [comment]
это как бы и есть релиз 0.3, давай перепроверю еще раз...

**Comment by apan65** [comment]
Тогда не знаю даже. Ладно, плевать.

**Comment by Rast1234** [comment]
перекачал релиз, проверил, работает... а, может в пароле символы какие-то ненормальные? `\` например?

**Comment by Rast1234** [comment]
мой лог выглядит так, скачал релизный архив, ввел свои логин-пароль в конфиг...
```
PS > dotnet .\VOffline.dll
2021-04-21 12:13:23,786 [  1] DEBUG  Started
2021-04-21 12:13:23,795 [  1] DEBUG  request check in
2021-04-21 12:13:24,492 [  1] DEBUG  FileCache.GoogleCheckIn.json saved value
2021-04-21 12:13:24,493 [  1] DEBUG  parse protobuf response
2021-04-21 12:13:24,497 [  1] DEBUG  mtalk build request
2021-04-21 12:13:24,502 [  1] DEBUG  mtalk tcp connect
2021-04-21 12:13:24,538 [  1] DEBUG  mtalk ssl authenticate
2021-04-21 12:13:24,609 [  1] DEBUG  mtalk send request
2021-04-21 12:13:24,610 [  1] DEBUG  mtalk read response
2021-04-21 12:13:24,648 [  1] INFO   success! GoogleCredentials(id ***; token ***)
2021-04-21 12:13:24,664 [  1] DEBUG  FileCache.GoogleCredentials.json saved value
2021-04-21 12:13:24,665 [  1] DEBUG  request receipt 1
2021-04-21 12:13:25,271 [  1] DEBUG  request receipt 2
2021-04-21 12:13:25,774 [  1] DEBUG  request non-refreshed token
2021-04-21 12:13:26,064 [  1] DEBUG  refresh token
2021-04-21 12:13:26,367 [  1] INFO   success! fresh token [***]
2021-04-21 12:13:26,370 [  1] DEBUG  FileCache.VkToken.json saved value
2021-04-21 12:13:26,590 [  8] DEBUG  Processing ["Audio","Docs","Photos","Video","Wall"] for [***]
```

**Comment by apan65** [comment]
С паролем\логином всё ок, обычные символы. 
После попытки получения токена ошибка >2021-04-21 14:14:50,805 [  1] DEBUG  request non-refreshed token
Короче плевать, спасибо за попытку помочь.

**Comment by Rast1234** [comment]
Окей, удачи. Если будет желание можно еще что-нибудь попробовать, у меня новая версия в другой ветке, ну и на твоего новорега могу сам попробовать зайти, потом пароль сменишь

**Comment by apan65** [comment]
Забавно но билд 0.1 работает.

**Comment by apan65** [comment]
блин, неужели из-за символов "//" это же комментирование

**Comment by apan65** [comment]
Короче, с версии 0.1 перенес кэши на 0.3, так работает всё. Такие костылики буду использовать.

**Comment by Rast1234** [comment]
Очень интересно... ну хорошо хоть как-то завелось. Кэш с токеном очень долгоиграющий вроде. Если что - переоткрывай issue)

**Comment by apan65** [comment]
В любом случае работает только 0.1 билд, на 0.3 это
```
2021-04-21 14:56:25,559 [  6] INFO   Cache saved: 0 items, C:\publish\.cache.voffline
2021-04-21 14:56:25,560 [  6] FATAL  System.NotImplementedException: The method or operation is not implemented.
   at VOffline.Services.Logic.ProcessTarget(Int64 id, DirectoryInfo dir, Mode mode, CancellationToken token, ILog log) in C:\vault\VOffline\VOffline\Services\Logic.cs:line 123
   at VOffline.Services.Logic.Run(CancellationToken token, ILog log) in C:\vault\VOffline\VOffline\Services\Logic.cs:line 84
   at VOffline.Program.Main(String[] args) in C:\vault\VOffline\VOffline\Program.cs:line 88
```

**Comment by Rast1234** [comment]
А это падает режим, который я не реализовал еще. В 0.1 он тож не будет работать. Скачивание видео или что-то еще такое

**Comment by Rast1234** [comment]
Работают только wall, audio, photos. Остальные просто не доделаны

**Comment by apan65** [comment]
> 
> 
> Работают только wall, audio, photos. Остальные просто не доделаны

Всё, все вопросы решены, спасибо

**Comment by apan65** [comment]
В wall тоже ошибка 

```
2021-04-21 16:35:49,892 [  7] DEBUG  0/2504, 100 items
2021-04-21 16:35:49,892 [  7] ERROR  Failed VOffline.Services.Handlers.WallHandler while working in [C:\publish\1\Wall]. Data is:

System.ArgumentException: Невозможно преобразовать в дату
Parameter name: response
   at VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
   at VkNet.Model.Attachments.Audio.FromJson(VkResponse response)
   at VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.Attachments.Post.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.WallGetObject.FromJson(VkResponse response)
   at VkNet.Categories.WallCategory.Get(WallGetParams params, Boolean skipAuthorization)
   at VkNet.Utils.TypeHelper.<>c__DisplayClass1_0`1.<TryInvokeMethodAsync>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at VOffline.Services.Vk.VkApiUtils.<>c__DisplayClass7_0.<<Posts>b__0>d.MoveNext() in C:\vault\VOffline\VOffline\Services\Vk\VkApiUtils.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at VOffline.Services.Vk.VkApiUtils.<>c__DisplayClass12_0`1.<<GetAllPagesAsync>b__1>d.MoveNext() in C:\vault\VOffline\VOffline\Services\Vk\VkApiUtils.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at VOffline.Services.Vk.VkApiUtils.GetAllPagesAsync[T](PageGetter`1 pageGetter, Decimal pageSize, CancellationToken token, ILog log, Boolean throwIfCountMismatch) in C:\vault\VOffline\VOffline\Services\Vk\VkApiUtils.cs:line 161
   at VOffline.Services.Handlers.WallHandler.ProcessInternal(Int64 id, DirectoryInfo workDir, CancellationToken token, ILog log) in C:\vault\VOffline\VOffline\Services\Handlers\WallHandler.cs:line 25
   at VOffline.Services.Handlers.HandlerBase`1.Process(T data, DirectoryInfo parentDir, CancellationToken token, ILog log) in C:\vault\VOffline\VOffline\Services\Handlers\HandlerBase.cs:line 27
2021-04-21 16:35:49,901 [ 36] INFO   All downloads completed. 0 successful, 0 failed
2021-04-21 16:35:49,911 [ 36] INFO   Cache saved: 634 items, C:\publish\.cache.voffline
```

**Comment by Rast1234** [comment]
А это уже ошибка VkNet(( дай ссылку на стену, на которой оно падает, че-нибудь придумаю вечером

**Comment by apan65** [comment]
wall14356037

**Comment by Rast1234** [comment]
я запилил злой костыль, теперь оно не падает на этапе обхода страниц. релиз 0.4 https://github.com/Rast1234/VOffline/releases/tag/0.4

**Comment by apan65** [comment]
> 
> 
> я запилил злой костыль, теперь оно не падает на этапе обхода страниц. релиз 0.4 https://github.com/Rast1234/VOffline/releases/tag/0.4

Спасибо вроде всё выкачало, ещё бы оболочку которая бы эти данные со стены с интерфейсом выводила.

**Comment by Rast1234** [comment]
Да тож думал но никак руки не доходят даже выкачивание сделать нормально))
